import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppPreferencesProvider } from "@/components/AppPreferencesProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitScript = `
  (() => {
    try {
      const raw = localStorage.getItem("pmp25_setup_preferences");
      const prefs = raw ? JSON.parse(raw) : {};
      const darkMode = prefs.darkMode !== false;
      const theme = darkMode ? "dark" : "light";
      const lang = prefs.chinese ? "zh" : "en";

      document.documentElement.dataset.theme = theme;
      document.documentElement.dataset.lang = lang;
      document.documentElement.lang = prefs.chinese ? "zh-Hant" : "en";
      document.documentElement.style.colorScheme = theme;
    } catch {
      document.documentElement.dataset.theme = "dark";
      document.documentElement.dataset.lang = "en";
      document.documentElement.style.colorScheme = "dark";
    }
  })();
`;

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <AppPreferencesProvider>{children}</AppPreferencesProvider>
      </body>
    </html>
  );
}
